  
name: Flutter CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.6'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Run Flutter analyzer
      run: flutter analyze
